leftnav:
- identifier: b95ac37a-f19b-50cb-1d90-a6348bf9195f
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 9fb184c7-2b78-bb4b-b8d0-9916f70b99f5
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: 1d2d75e6-8a20-e444-ae63-453e00c24adf
  name: Readings
  url: /pages/readings
  weight: 30
- identifier: 62bee747-eb37-c110-3960-f5474b41cfe6
  name: Assignments
  url: /pages/assignments
  weight: 40
- identifier: 25da5339-4c2b-7427-d2d9-80efed8dc8a1
  name: Projects
  url: /pages/projects
  weight: 50
- identifier: e1ea2d99-f88d-f855-fe8f-532a7d8e76cc
  name: Maps
  url: /pages/maps
  weight: 60
